# Generated by Django 3.2.8 on 2022-11-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedoc', '0006_document_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vislist',
            field=models.TextField(null=True),
        ),
    ]
