# Generated by Django 3.2.8 on 2022-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedoc', '0007_document_vislist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='vislist',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
